# Generated by Django 3.2.25 on 2025-02-16 21:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryptedData', models.BinaryField()),
                ('dateRegister', models.DateField()),
                ('dateEffect', models.DateField()),
                ('value', django_cryptography.fields.encrypt(models.FloatField(default=0.0))),
                ('metricRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fitness.metric')),
            ],
        ),
    ]
