# Generated by Django 3.2.25 on 2025-02-18 23:01

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDebt', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nextDateExpected', models.DateField()),
                ('businessDay', models.CharField(choices=[('A', 'Qualquer Dia'), ('BW', 'Dia útil ANTERIOR'), ('WB', 'Dia útil POSTERIOR')], max_length=3)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('user_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('transactionserie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Finances.transactionserie')),
                ('juro', models.FloatField()),
            ],
            bases=('Finances.transactionserie',),
        ),
        migrations.CreateModel(
            name='PlannedEvent',
            fields=[
                ('transactionserie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Finances.transactionserie')),
                ('isFixedDate', models.BooleanField(default=True)),
                ('cycle', models.CharField(choices=[('S', 'Semanal'), ('BiS', 'Bisemanal'), ('M', 'Mensal'), ('Tri', 'Trimestral'), ('SeM', 'Semestral'), ('A', 'Anual')], max_length=4)),
                ('isFixedValue', models.BooleanField(default=True)),
                ('expectValue', models.FloatField()),
                ('tags', models.ManyToManyField(to='Finances.Tag')),
            ],
            bases=('Finances.transactionserie',),
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houses', models.ManyToManyField(to='Finances.House')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('activeHouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finances.house')),
                ('monthRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finances.month')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDebt', models.BooleanField(default=True)),
                ('value', models.FloatField()),
                ('dateRegister', models.DateField(auto_now_add=True)),
                ('dateEffect', models.DateField()),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('directDebt', models.BooleanField(blank=True, default=False)),
                ('mb_reference', models.CharField(blank=True, max_length=20)),
                ('mb_entity', models.CharField(blank=True, max_length=20)),
                ('IBAN', models.CharField(blank=True, max_length=36)),
                ('paymentDescription', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=35, unique=True)),
                ('description', models.TextField()),
                ('monthReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finances.month')),
                ('tags', models.ManyToManyField(to='Finances.Tag')),
                ('user_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finances.plannedevent')),
                ('fromCreditCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromCC', to='Finances.creditcard')),
                ('toCreditCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finances.creditcard')),
            ],
        ),
    ]
