# Generated by Django 3.2.25 on 2025-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Name',
            field=models.CharField(max_length=25),
        ),
    ]
